[Rule]
DOMAIN-KEYWORD,patentexam,DIRECT
FINAL,DIRECT
[Proxy Group]
手动选择 = select,赔钱机场,use=true,interval=86400,timeout=5,url=http://www.gstatic.com/generate_204

[URL Rewrite]
^https:\/\/app2.patentexam.com.* direct

[Script]
usecar=type=http-response,pattern=https://app2.patentexam.com.cn/nbtaxi/api/punch/queryWorkPointList,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ilzge/usecar/main/usecar.js,script-update-interval=0

[MITM]
hostname = %APPEND% *.patentexam.com.cn
